### ISSUE TITLE
Extender adds dependencies to all module extensions

### ISSUE THREAD

**Issue by mikesir87** [mariocasciaro/angular-extender#1]
If I am building a project in which an angular module is being built over multiple files, the plugin updates all locations where the module definition occurs.  For example:

```
// app.js
angular.module("someApp", ["ui.router"])
    .config(......);

// controller.js
angular.module("someApp")
    .controller("Controller", ....);
```

If I have a stream that has all JavaScript files in it and run the extender, both app.js and controller.js are updated to look like:

```
// app.js
angular.module("someApp", ["ui.router", "templates"])
    .config(......);

// controller.js
angular.module("someApp", ['templates'])
    .controller("Controller", ....);
```

This then breaks the app since the module is being declared multiple times and the last guy wins.

It'd if it updates ONLY the module location where a definition already exists.  For example, while traversing, the extender finds that app.js already has a dependency definition and updates it there.

**Comment by mariocasciaro** [comment]
Fixed in 0.2.0. Thanks for reporting.

**Comment by mikesir87** [comment]
Thanks for the quick response and publish!

**Comment by mariocasciaro** [comment]
:+1: was an easy fix :smile:
